### ISSUE TITLE
Are JPEGDecoder and GIFEncoder real packages?

### ISSUE THREAD

**Issue by fregante** [devongovett/neuquant#1]
I saw the example in the readme, are they real streaming d/encoders or is it just an example?

**Comment by devongovett** [comment]
Yes. See [jpg-stream](https://github.com/devongovett/jpg-stream) and [gif-stream](https://github.com/devongovett/gif-stream).

**Comment by fregante** [comment]
![amazed-rage-face](https://cloud.githubusercontent.com/assets/1402241/9612438/927592b6-509a-11e5-8717-8e17fc7c016f.jpg)
